### ISSUE TITLE
The provided ScrollController is currently attached to more than one ScrollPosition.

### ISSUE THREAD

**Issue by mark8044** [optimist-dev/scrolls_to_top#3]
I immediately get that error when I implemented ScrollsToTop onto of my listview

```
The following assertion was thrown while notifying status listeners for AnimationController:
The provided ScrollController is currently attached to more than one ScrollPosition.

The Scrollbar requires a single ScrollPosition in order to be painted.

When the scrollbar is interactive, the associated Scrollable widgets must have unique ScrollControllers. The provided ScrollController must be unique to a Scrollable widget.

When the exception was thrown, this was the stack: 
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1333:9)
#1      RawScrollbarState._debugCheckHasValidScrollPosition (package:flutter/src/widgets/scrollbar.dart:1357:6)
#2      RawScrollbarState._validateInteractions (package:flutter/src/widgets/scrollbar.dart:1272:14)
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:233:19)
#4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:815:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:749:5)
#6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:612:12)
#7      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:494:12)
#8      RawScrollbarState._maybeStartFadeoutTimer.<anonymous closure> (package:flutter/src/widgets/scrollbar.dart:1451:37)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
The AnimationController notifying status listeners was: AnimationController#8c86a(◀ 1.000)
```

**Comment by otopba** [comment]
Can you provide a minimal example and I'll try to figure out how to fix it?

**Comment by otopba** [comment]
Due to the fact that there has been no response for a long time, I am closing this thread. If the problem recurs, please write to this thread again
